checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  environment:
    python: 3.7.1
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
          - pylint-run loglan_db

filter:
    excluded_paths:
        - tests/*
