os: linux
dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements-tests.txt
# command to run tests
script:
  - pytest --cov=loglan_db tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ocular --data-file ".coverage" --config-file ".coveragerc"